### ISSUE TITLE
Not able to visit the Admin User Interface, ota-user-profile: System error

### ISSUE THREAD

**Issue by adlingepa** [advancedtelematic/ota-community-edition#105]
I am trying to setup the ostree meta-update yocto build environment and OTA CE server on same VM server machine.
I am able to setup the OTA CE server using make start with docker as minikube driver.
But while trying to access the Admin user interface using http://app.ota.local url, this url is redirected to http://app.ota.local/login page automatically and gives error as "ota-user-profile: System error"

I've check below things while troubleshooting this,
All microservices are running,
```
prashanta@hiuyoctovmnew:/u02/ats_repo_poky/build/tmp$ kubectl get pods
NAME                                      READY   STATUS    RESTARTS   AGE
app-76cccf7cb4-fzw6h                      1/1     Running   0          4d
campaigner-76cf7cc696-bkjrp               1/1     Running   895        4d
campaigner-daemon-6c99974f96-p8sb2        1/1     Running   0          4d
device-registry-68fbc6d858-f499g          1/1     Running   0          4d
device-registry-daemon-6c4b5989cc-9j8l7   1/1     Running   0          4d
director-57d4758bc5-msjxl                 1/1     Running   0          4d
director-daemon-5fdd469fd6-hlm9h          1/1     Running   1          4d
gateway-deployment-6567f4d664-k5q7c       1/1     Running   0          4d
kafka-0                                   1/1     Running   0          4d
mysql-0                                   1/1     Running   0          4d
treehub-0                                 1/1     Running   3          4d
tuf-keyserver-68c654d575-5dkd4            1/1     Running   0          4d
tuf-keyserver-daemon-5d6c475575-z8fmn     1/1     Running   0          4d
tuf-reposerver-684b7b8f7c-4glk7           1/1     Running   0          4d
web-events-7f8645678-4p7m8                1/1     Running   3          4d
zookeeper-0                               1/1     Running   0          4d

```
tried to accessing via http tool,
```
prashanta@hiuyoctovmnew:/u02/ats_repo_poky/build/tmp$ http http://app.ota.local
HTTP/1.1 303 See Other
Connection: keep-alive
Content-Length: 0
Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-eval'  https://cdn.auth0.com https://cdn.eu.auth0.com https://  https://js-agent.newrelic.com/ https://bam.nr-data.net/ https://tags.tiqcdn.com 'self' 'unsafe-inline' https://wego.here.com/services/iplookup/ ; style-src 'unsafe-inline' 'self' maxcdn.bootstrapcdn.com https://tags.tiqcdn.com; font-src 'self' data: cdn.auth0.com maxcdn.bootstrapcdn.com; img-src 'self' data: cdn.auth0.com https://*.gravatar.com https://*.githubusercontent.com https://*.googleusercontent.com https://*.wp.com https://sheredeutschlandgmbh.d1.sc.omtrdc.net; connect-src 'self' ws://*.ota.local:80 https://bam.nr-data.net/  https://
Date: Mon, 31 Aug 2020 11:22:14 GMT
Location: /login
Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
Server: nginx/1.13.9
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Permitted-Cross-Domain-Policies: master-only
X-XSS-Protection: 1; mode=block
x-b3-traceid: 0038c31551b4e50d

```
Below the browser screenshot,
![Screenshot from 2020-08-31 16-47-56](https://user-images.githubusercontent.com/32295474/91714668-dc862280-eba9-11ea-886c-75c0446da14b.png)

Please help me in troubleshooting this issue.

Thanks ,
Prashant

**Comment by ddunlap2005** [comment]
@adlingepa About 8 months ago, commit https://github.com/advancedtelematic/ota-plus-server/commit/b03ac42d3537007aa2f3cba637c278e575cc78e0 was introduced. This commit adds a call to userProfileApi within the NoLoginAction. OTA Community Edition does not use the ota-user-profile that I can see; Ota-plus-server does not even define the USER_PROFILE_HOST/PORT environment variables.

I was able to bring my Ota-community-edition server up earlier without seeing this error when I connected to app.ota.local. I corrected a few more issues with the environment and now I'm seeing this error. If I figure out why I got past it, I'll let you know.

**Comment by houcros** [comment]
ota-plus-server always had a reference to ota-user-profile, see https://github.com/advancedtelematic/ota-plus-server/blob/f1c3fc86e76b6d950e8c24af7fc5731fb2ef7c4f/ota-plus-web/conf/application.conf#L255. The thing is that, somewhere along the way, ota-plus-server became more dependent on ota-user-profile, to a point where it won't work without it. But ota-user-profile is not part of the CE, hence the problems.

I guess one could implement a new `NoLoginAction` to do the same that the old one was doing, but I'm afraid that would only uncover further issues of the same nature.

**Comment by msatpathy26** [comment]
This issue still persists and keeps coming back every now and then. Not able to open an issue in ota-plus-server repo as well.

**Comment by karymei** [comment]
Is there any plan to fix this issue? Thanks.

**Comment by houcros** [comment]
Sorry, but I don't think so. To the best of my knowledge, this repo is not actively maintained.

**Comment by wzq619** [comment]
I got the same issue，do anyone have the solution?thanks!

**Comment by simao** [comment]
I believe a patch like the following would allow the webapp to be used without user-profile, which is a closed source component:

https://gist.github.com/simao/3b347729c568c8929422fce57efc222a

However, like houcros said this project is not actively maintained, further development will continue at https://github.com/uptane/ota-community-edition Though a web frontend is not supported and the ota ce solution is api based **only**.

**Comment by lpcysmi** [comment]
> 
> 
> I believe a patch like the following would allow the webapp to be used without user-profile, which is a closed source component:
> 
> https://gist.github.com/simao/3b347729c568c8929422fce57efc222a
> 
> However, like houcros said this project is not actively maintained, further development will continue at https://github.com/uptane/ota-community-edition Though a web frontend is not supported and the ota ce solution is api based **only**.



Where do I apply this patch?

I have been trying to use https://github.com/uptane/ota-community-edition  and always end up at this error.

**Comment by simao** [comment]
You'll need to apply that patch on the webapp (https://github.com/advancedtelematic/ota-plus-server) build a webpp container, and make ota-community edition use that container.

**Comment by jinlingyi** [comment]
Are there any guide to resolve this issue now?

> You'll need to apply that patch on the webapp (https://github.com/advancedtelematic/ota-plus-server) build a webpp container, and make ota-community edition use that container.

How to use this as web app of OTA CE?

**Comment by simao** [comment]
This project is no longer under active development, you can use https://github.com/uptane/ota-community-edition which doesn't use a web app, or you can apply that patch to webapp yourself. 

Again, this is not supported, but you can just 

```
git checkout <webapp>
git apply user-profile-disable.patch
sbt docker:publishLocal
```

Use that image instead of the one included in this repo.

If you are just trying ota-ce and see how it works you could try https://github.com/simao/ota-lith there is a `webapp` branch with a web ui.

**Comment by jinlingyi** [comment]
> This project is no longer under active development, you can use https://github.com/uptane/ota-community-edition which doesn't use a web app, or you can apply that patch to webapp yourself.
> 
> Again, this is not supported, but you can just
> 
> ```
> git checkout <webapp>
> git apply user-profile-disable.patch
> sbt docker:publishLocal
> ```
> 
> Use that image instead of the one included in this repo.
> 
> If you are just trying ota-ce and see how it works you could try https://github.com/simao/ota-lith there is a `webapp` branch with a web ui.

Thank you for your reply! But the https://github.com/uptane/ota-community-edition has the same issue. Will it be updated?
I will try your patch for this issue.

**Comment by simao** [comment]
See my comments on those projects.

**Comment by jinlingyi** [comment]
> See my comments on those projects.

Thank you very much! Now I can run this branch too. And the web UI can find device with qemu.
But the web UI can't create update and campaigner, and the ota-cli can't control this project.
This feature can only be used with API?

**Comment by simao** [comment]
in which project are you having problems with ota-cli?

in which projet are you having problems with the web ui creating updates? And what exactly is the error?

in which project are you having trouble using ota-cli? ota-cli should be able to be used with both. See https://github.com/simao/ota-lith/blob/master/docs/updates-ota-cli.md

**Comment by jinlingyi** [comment]
The web UI of advancedtelematic/ota-community-edition (also the local docker image of advancedtelematic/ota-plus-server) can't create update, the button of 'Create update' is missing.
And I can't set ota-cli with advancedtelematic/ota-community-edition because when I use 'ota init' the servers seems can't be    reach of 'http://campaigner.ota.local, etc.', even if I set it with Ingress.

**Comment by jinlingyi** [comment]
Now I can use the web UI to create update. I change the UIFeature to all open in the ota-plus-server.
Thank you for your reply!

**Comment by Jeredriq** [comment]
@jinlingyi 
Can you please provide the road you take step by step?
